config/routes.rb
# frozen_string_literal: true

RedmineApp::Application.routes.draw do
  get 'secret_santa', to: 'secret_santa#index', as: :secret_santa

  resources :secret_santa_players, controller: 'secret_santa_players'
  resources :secret_santa_games, controller: 'secret_santa_games' do
    member do
      post :draw
      post :send_emails
    end
  end
end

app/models/secret_santa/assignment.rb
# frozen_string_literal: true

module SecretSanta
  class Assignment < ActiveRecord::Base
    self.table_name = 'secret_santa_assignments_new'

    belongs_to :game, class_name: 'SecretSanta::Game', foreign_key: :secret_santa_game_id
    belongs_to :giver, class_name: 'SecretSanta::Player', foreign_key: :giver_id
    belongs_to :receiver, class_name: 'SecretSanta::Player', foreign_key: :receiver_id

    def self.count_for_player(player_id)
      where(giver_id: player_id).count
    end
  end
end

app/models/secret_santa/game.rb
# frozen_string_literal: true

class NotEnoughPlayersError < StandardError; end

module SecretSanta
  class Game < ActiveRecord::Base
    self.table_name = 'secret_santa_games'

    has_many :assignments, class_name: 'SecretSanta::Assignment', foreign_key: :secret_santa_game_id, dependent: :destroy

    validates :name, presence: true

    def draw!
      players = SecretSanta::Player.order(created_at: :desc)
      raise NotEnoughPlayersError if players.size < 2

      shuffled = players.shuffle

      game_assignments = shuffled.each_with_index.map do |giver, idx|
        receiver = shuffled[(idx + 1) % shuffled.size]
        {giver_id: giver.id, receiver_id: receiver.id}
      end

      assignments.delete_all
      game_assignments.shuffle.each { |attrs| assignments.create!(attrs) }
    end

    def send_santa_emails
      assignments.each do |assignment|
        SecretSantaMailer.santa_email(assignment.giver.user, assignment).deliver_now
      end
    end
  end
end

app/models/secret_santa/player.rb
# frozen_string_literal: true

module SecretSanta
  class Player < ActiveRecord::Base
    self.table_name = 'secret_santa_players_new'
    self.primary_key = 'id'

    belongs_to :user, class_name: 'User', foreign_key: :id

    validates :id, presence: true, uniqueness: true
    validates :want_to_get, length: {maximum: 2000}
    validates :dont_want_to_get, length: {maximum: 2000}
  end
end

app/controllers/secret_santa_controller.rb
# frozen_string_literal: true

class SecretSantaController < ApplicationController
  before_action :require_login

  helper SecretSanta::SecretSantaHelper

  def index
    @players = SecretSanta::Player.order(created_at: :desc)
    @games = SecretSanta::Game.order(created_at: :desc)
  end
end

app/controllers/secret_santa_games_controller.rb
# frozen_string_literal: true

class SecretSantaGamesController < ApplicationController
  before_action :require_login
  before_action :authorize_admin
  before_action :set_game, only: %i[show edit update destroy draw send_emails]

  helper SecretSanta::SecretSantaHelper

  def show
    render('secret_santa/games/show')
  end

  def new
    @game = SecretSanta::Game.new

    @available_players = SecretSanta::Player.all
    render('secret_santa/games/new')
  end

  def edit
    render('secret_santa/games/edit')
  end

  def create
    @game = SecretSanta::Game.new(game_params)
    if @game.save
      redirect_to(secret_santa_game_path(@game), notice: l(:notice_successful_create))
    else
      @available_players = SecretSanta::Player.all
      render('secret_santa/games/new')
    end
  end

  def update
    if @game.update(game_params)
      redirect_to(secret_santa_game_path(@game), notice: l(:notice_successful_update))
    else
      render('secret_santa/games/edit')
    end
  end

  def draw
    begin
      @game.draw!
      flash[:notice] = l(:label_draw_successful)
    rescue NotEnoughPlayersError
      flash[:error] = l(:error_not_enough_players)
    rescue StandardError => e
      flash[:error] = "#{l(:error_draw_failed)}: #{e.message}"
    end

    redirect_to(secret_santa_game_path(@game))
  end

  def send_emails
    if @game.assignments.exists?
      @game.send_santa_emails
      flash[:notice] = l(:label_emails_has_ben_sent)
    else
      flash[:error] = l(:error_no_assignment_found)
    end
    redirect_to(secret_santa_game_path(@game))
  end

  def destroy
    @game.destroy
    redirect_to(secret_santa_path, notice: l(:notice_successful_delete))
  end

private

  def authorize_admin
    return if User.current.admin?

    redirect_to(secret_santa_path)
  end

  def set_game
    @game = SecretSanta::Game.find(params[:id])
  end

  def game_params
    params.require(:secret_santa_game).permit(:name, :message)
  end
end

app/controllers/secret_santa_players_controller.rb
# frozen_string_literal: true

class SecretSantaPlayersController < ApplicationController
  before_action :require_login
  before_action :set_player, only: %i[edit update destroy]

  helper SecretSanta::SecretSantaHelper

  def new
    @player = SecretSanta::Player.new
    render('secret_santa/players/new')
  end

  def edit
    if params[:id].to_i == User.current.id
      render('secret_santa/players/edit')
    else
      redirect_to(secret_santa_path)
    end
  end

  def create
    @player = SecretSanta::Player.new(player_params.merge(id: User.current.id))
    if @player.save
      redirect_to(secret_santa_path, notice: l(:notice_successful_create))
    else
      render('secret_santa/players/new')
    end
  end

  def update
    return render_403 unless @player.id == User.current.id || User.current.admin?

    if @player.update(player_params)
      redirect_to(secret_santa_path, notice: l(:notice_successful_update))
    else
      render('secret_santa/players/edit')
    end
  end

  def destroy
    return render_403 unless @player.id == User.current.id || User.current.admin?

    assignments_count = SecretSanta::Assignment.count_for_player(@player.id)
    if assignments_count.positive?
      flash[:error] = l(:error_participated_to_assignment, assignments_count: assignments_count)
      redirect_to(secret_santa_path)
      return
    end

    if @player.destroy
      flash[:notice] = l(:notice_successful_delete)
    else
      flash[:error] = "#{l(:error_player_deletion_failed)}: #{@player.errors.full_messages.join(', ')}"
    end

    redirect_to(secret_santa_path)
  end

private

  def set_player
    @player = SecretSanta::Player.find(params[:id])
  end

  def player_params
    params.require(:secret_santa_player).permit(:want_to_get, :dont_want_to_get)
  end
end

app/helpers/secret_santa/secret_santa_helper.rb
# frozen_string_literal: true

module SecretSanta
  module SecretSantaHelper
    def player_actions(player)
      links = []
      links << link_to(l(:button_edit), edit_secret_santa_player_path(player.id)) if User.current.id == player.id
      links << link_to(l(:button_delete), secret_santa_player_path(player.id), data: {confirm: l(:text_are_you_sure)}, method: :delete) if User.current.id == player.id || User.current.admin?

      safe_join(links, ' | ')
    end

    def game_actions(game)
      links = []
      links << link_to(l(:button_show), secret_santa_game_path(game))
      links << link_to(l(:button_edit), edit_secret_santa_game_path(game))
      links << link_to(l(:button_delete), secret_santa_game_path(game), method: :delete, data: {confirm: l(:text_are_you_sure)})

      safe_join(links, ' | ')
    end

    def email_presence(player)
      if player.mail.present?
        l(:label_email_information, address: player.mail)
      else
        l(:hint_add_an_email_to_account)
      end
    end

    def santa_letter_text_area(game, mailing_options = {})
      letter_text = game.message
      text_area_tag('secret_santa_game[message]', letter_text, mailing_options).html_safe
    end
  end
end

app/views/secret_santa/games/_form.html.erb
<h1><%= l(:label_write_an_email) %></h1>
<p><%= l(:hint_template_variables) %></p>

<%= form_for @game do |f| %>
  <p>
    <%= f.label :name, l(:field_subject) %>
    <%= f.text_field :name, :size => 100 %>
  </p>

  <p>
    <%= f.label :message, l(:field_message) %>
    <%= santa_letter_text_area(@game, :label => false, :class => 'wiki-edit', :rows => 10) %>
    <%= wikitoolbar_for('secret_santa_game_message') %>
  </p>

  <p>
    <%= f.submit l(:button_save) %>
  </p>
<% end %>

app/views/secret_santa/games/_list.html.erb
<% if @games.nil? || @games.count.zero? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  <table class="list">
    <thead>
    <tr>
      <th><%= l(:field_subject) %></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game_actions(game) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/secret_santa/games/edit.html.erb
<h2><%= link_to l(:label_secret_santa_games), secret_santa_path %> » <%= l(:button_edit) %></h2>

<%= render('secret_santa/games/form') %>

app/views/secret_santa/games/new.html.erb
<h2><%= link_to l(:label_secret_santa_games), secret_santa_path %> » <%= l(:button_create) %></h2>

<%= render('secret_santa/games/form') %>

app/views/secret_santa/games/show.html.erb
<h2><%= link_to l(:label_secret_santa_games), secret_santa_path %> » <%= l(:button_show) %></h2>

<h2><%= @game.name %></h2>
<p><%= textilizable(@game.message) %></p>
<%= button_to l(:button_edit), edit_secret_santa_game_path(@game), method: :get %>

<div class="line"></div>

<% if User.current.admin? %>
  <h2><%= l(:label_secret_santa_players) %></h2>

  <% if @game.assignments.exists? %>
    <% @game.assignments.each do |a| %>
      <p><%= a.giver.user.try(:name) %> (<%= a.giver.user.try(:mail) %>)</p>
    <% end %>

    <%= button_to l(:label_update_players_list), draw_secret_santa_game_path(@game),
                  method: :post, class: 'btn btn-primary' %>

    <%= button_to l(:label_sent_emails), send_emails_secret_santa_game_path(@game),
                  method: :post, data: { confirm: l(:hint_send_emails) }, class: 'btn btn-primary' %>
  <% else %>
    <p><%= l(:label_no_data) %></p>

    <%= button_to l(:label_add_all_player_and_draw), draw_secret_santa_game_path(@game),
                  method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>


<style>
    .line {
        height: 1px;
        background: #ccc;
        margin: 16px 0;
    }
</style>

app/views/secret_santa/index.html.erb
<h1><%= link_to l(:label_secret_santa), secret_santa_path %></h1>

<% if User.current.admin? %>
  <h2><%= l(:label_secret_santa_games) %></h2>
  <% if @games.nil? %>
    <h3><%= l(:hint_create_game) %></h3>
  <% end %>
  <div class="contextual">
    <%= link_to l(:button_create), new_secret_santa_game_path, class: 'icon icon-add' %>
  </div>
  <%= render partial: 'secret_santa/games/list', locals: { games: @games } %>
<% end %>

<h2><%= l(:label_secret_santa_players) %></h2>
<% unless SecretSanta::Player.exists?(id: User.current.id) %>
  <h3><%= l(:hint_create_member) %></h3>
  <div class="contextual">
    <%= link_to l(:button_create_member), new_secret_santa_player_path, class: 'icon icon-add' %>
  </div>
<% end %>
<%= render partial: 'secret_santa/players/list', locals: { players: @players } %>

app/views/secret_santa/players/_form.html.erb
<%= form_for @player do |f| %>
  <p><strong><%= User.current.name %></strong></p>
  <p><strong><%= email_presence(User.current) %></strong></p>

  <p>
    <%= f.label :want_to_get, l(:field_want_to_get) %><br>
    <%= f.text_area :want_to_get, rows: 4, cols: 60 %>
  </p>

  <p>
    <%= f.label :dont_want_to_get, l(:field_dont_want_to_get) %><br>
    <%= f.text_area :dont_want_to_get, rows: 4, cols: 60 %>
  </p>

  <%= f.submit l(:button_save) %>
<% end %>

app/views/secret_santa/players/_list.html.erb
<% if @players.nil? || @players.count.zero? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  <table class="list">
    <thead>
    <tr>
      <th><%= l(:label_user) %></th>
      <th><%= l(:field_mail) %></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.user.name %></td>
        <td><%= player.user.mail %></td>
        <td><%= player_actions(player) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/secret_santa/players/edit.html.erb
<h2><%= link_to l(:label_secret_santa_players), secret_santa_path %> » <%= l(:button_edit) %></h2>

<%= render('secret_santa/players/form') %>

app/views/secret_santa/players/new.html.erb
<h2><%= link_to l(:label_secret_santa_players), secret_santa_path %> » <%= l(:button_create) %></h2>

<%= render('secret_santa/players/form') %>